# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Paperless-NG
version: "1.5.0"
slug: paperless
description: Paperless is an application by Daniel Quinn and contributors that indexes your scanned documents and allows you to easily search for documents and store metadata alongside your documents.
url: "https://github.com/jonaswinkler/paperless-ng"
arch:
  - armv7
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 8000
watchdog: http://[HOST]:[PORT:8000]/
image: "ghcr.io/danto7/home-assistant/paperless-ng-addon-{arch}"
