name: "Ingress Example"
version: "1.0.2"
slug: "nginx"
description: "Ingress testing"
arch:
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
image: "ghcr.io/danto7/home-assistant-ingress-addon-{arch}"
